const ProviderData = [
  {
    name: "WayCloud",
    cost: 1260,
    availability: 97.5,
    usability: "Medium",
    security_management: "Low",
    flexibility: "Low",
    response_time: 302.75,
    id: 11,
    img: "https://img.icons8.com/color-glass/48/000000/cloud-user.png",
  },
  {
    name: "AWS",
    cost: 1500,
    availability: 99.99,
    usability: "High",
    security_management: "High",
    flexibility: "Medium",
    response_time: 100.5,
    id: 12,
    img: "https://img.icons8.com/color-glass/48/000000/cloud-user.png",
  },
  {
    name: "DAVV Cloud",
    cost: 10000,
    availability: 50.0,
    usability: "Low",
    security_management: "Medium",
    flexibility: "High",
    response_time: 100.5,
    id: 123,
    img: "https://img.icons8.com/color-glass/48/000000/cloud-user.png",
  },
  {
    name: "Salesforces",
    cost: 1050,
    availability: 98.6,
    usability: "Medium",
    security_management: "High",
    flexibility: "Medium",
    response_time: 159.6,
    id: 13,
    img: "https://img.icons8.com/color-glass/48/000000/cloud-user.png",
  },
  {
    name: "Azure",
    cost: 2000,
    availability: 99.99,
    usability: "High",
    security_management: "High",
    flexibility: "High",
    response_time: 80.5,
    id: 14,
    img: "https://img.icons8.com/color-glass/48/000000/cloud-user.png",
  },
  {
    name: "Rateeval",
    cost: 500,
    availability: 90.54,
    usability: "Low",
    security_management: "Low",
    flexibility: "Medium",
    response_time: 548.2,
    id: 15,
    img: "https://img.icons8.com/color-glass/48/000000/cloud-user.png",
  },
  {
    name: "GCP",
    cost: 1850,
    availability: 99,
    usability: "High",
    security_management: "High",
    flexibility: "Medium",
    response_time: 120.6,
    id: 16,
    img: "https://img.icons8.com/color-glass/48/000000/cloud-user.png",
  },
];

export default ProviderData;
