export const SETUP_USER_BEGIN = "SET_UP_USER";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";
export const HIDE_ALERT = "HIDE_ALERT";
export const SET_USER_REQUIREMENT = "SET_USER_REQUIREMENT";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOGOUT_USER = "LOGOUT_USER";
export const SET_ALERT = "SET_ALERT";
